%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RESUME CLASS FILE
%
% This class file defines the structure and design of the template. 
%
%
%
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%----------------------------------------------------------------------------------------
%   CLASS DECLARATION (Loads base class article as well)
%----------------------------------------------------------------------------------------
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{resume}[2021/03/20 Resume Class v0.1]
\LoadClass[11pt,letterpaper]{article} % Font size and paper type

%----------------------------------------------------------------------------------------
%   CLASS FORMATTING PACKAGES
%----------------------------------------------------------------------------------------
\RequirePackage[parfill]{parskip}   % Remove paragraph indentation
\RequirePackage{ifthen}             % Required for ifthenelse statements

\pagestyle{empty} % Suppress page numbers

%----------------------------------------------------------------------------------------
%   CUSTOM RESUME ENVIRONMENTS
%----------------------------------------------------------------------------------------
